### ISSUE TITLE
can authenticate method have an async call to another application server?

### ISSUE THREAD

**Issue by ashwaniare** [johnballantyne/qbws#2]
Hi John, 
I am writing a service gateway for an application which will eventually do the API management to serve the requests of third party applications, such as the Quickbooks to fetch and feed information. So that is kind of a middle tier running a SOAP server(where the QB webservice is deployed) in between the QBWC and my application. The problem is, for authentication also I need to do an async call to my application. Now in case of sendRequestXML that was possible with 'NoOp' as a response. Is there any way you can suggest by which async call within the authenticate web mehtod can be made or any other workaround?
Thanks in advance!

**Comment by johnballantyne** [comment]
`authenticate()` has a structure similar to `sendRequestXML()` — you can specify return values to tell the Web Connector to try again later. One of the examples on page 63 of the _QuickBooks Web Connector Programmer’s Guide_ shows how:

> Sample behavior of `authRet[2]` & `authRet[3]` is as follows:
> 
> **Example 1.** Suppose `authRet[1]=""`, `authRet[2]=”x”` seconds and `authRet[3]=””`
> Result: the update is postponed by x seconds. In the QBWC status window this will be
> shown:
> 
> Last Result- Update postponed by application

You could do the same as we talked about with `sendRequestXML()`, set a flag outside the authenticate method and have another function asynchronously fetch the required credentials and flip the flag for the next authentication attempt. You should be careful to actually verify those credentials within your qbws, otherwise you're opening up a security hole since there is no session ticket until after successful authentication.

Admittedly this isn't a very elegant way to accomplish this, so I'd like to eventually try and explore other options. Reworking the whole utility with an asynchronous design could be quite useful.

**Comment by ashwaniare** [comment]
I am new to this whole javascript thing but I got the point. Thanks again!
